apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - host: kong.example
    http:
      paths:
      - path: /produits
        pathType: ImplementationSpecific
        backend:
          service:
            name: produits-service
            port:
              number: 9001