apiVersion: v1
kind: Service
metadata:
  name: microservice-commandes-service
spec:
  selector:
    app: microservice-commandes
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: NodePort
